#!/bin/sh
clear; CUR=$(pwd); OLD=$CUR; . /etc/init.d/tc-functions; . ../functions;       ##### TCL
TITLE="
${CYAN}        ######
${CYAN}       ##    ## ####
${CYAN}       ##        ##  ##     ##
${CYAN}        ######   ##  ###   ### ########
${CYAN}             ##  ##  #### #### ##     ## ##
${CYAN}       ##    ##  ##  ## ### ## ##     ## ##       ########
${CYAN}        ######   ##  ##     ## ########  ##       ##
${CYAN}                #### ##     ## ##        ##       ##             ${WHITE}#####
${CYAN}                     ##     ## ##        ##       ######        ${WHITE}##   ##
${CYAN}                   #           ##        ##       ##            ${WHITE}# ${BLUE}0 0 ${WHITE}#
${CYAN}  ######          ###                    ######## ##           ${WHITE}#   ${YELLOW}V   ${WHITE}#
${CYAN}    ##             #                              ########    ${WHITE}##       ##
${CYAN}    ##         ###    ### ####   ###    ###  ##### #####     ${WHITE}#           #
${CYAN}    ##        #  ##    ###    ##  ##     ##    ##   ##      ${WHITE}#             #
${CYAN}    ##       #   ##    ##     ##  ##     ##      ###        ${WHITE}#  #       #  #
${CYAN}    ##          ###    ##     ##  ##     ##      ###       ${YELLOW}@@${WHITE}##         ##${YELLOW}@@
${CYAN}    ##       # ###     ##     ##  ##     ##     ## ##    ${YELLOW}@@@@@@${WHITE}#       #${YELLOW}@@@@@@
${CYAN}    ##      ## ### #   ##     ##  ###   ###    ##   ##   ${YELLOW}@@@@@@@${WHITE}# ${RED}CDC ${WHITE}#${YELLOW}@@@@@@@
${CYAN}  ############  ###   ####   ####   #### ### ##### #####   ${YELLOW}@@@@@${WHITE} ##### ${YELLOW}@@@@@"
#------------------------------------------------------------------------------#
# This file is a part of a project which contains pieces from other projects   #
# belonging to potentially hundreds of individuals globally in an effort to    #
# bring together some of the best computing materials the world has to offer   #
# under a single roof with an automated core allowing a tailor-made experience #
# like no other. Some of these pieces may have originated from individuals,    #
# while others may have come from public distributions such as Alpine, Apache, #
# CentOS, Debian, Fedora, SlackWare, TinyCore, Zorin, etc. just to name a few. #
# This project will be ever changing throughout the entire Version 0.x.x life- #
# cycle and should NOT be considered a complete and/or functional system.      #
#------------------------------------------------------------------------------#
echo "${TITLE}${NORMAL}"; echo; SFX=$(GetProcessorType)
SXX=${SFX/x86_/x}; export CFLAGS CXXFLAGS LDFLAGS

echo -n "${CYAN}Loading support extensions:${NORMAL}"
##ExtClean
ExtLoad wget; echo

cd $CUR; mkdir -p $CUR/bin $CUR/src
[ ! -f $CUR/versions.lst ] && touch $CUR/versions.lst


















################
## util-linux ##
################
cd $CUR; echo "${CYAN}Package ${GREEN}util-linux${NORMAL}"
echo -n "${CYAN}Loading support extensions:${NORMAL}"
ExtLoad compiletc sqlite3-dev file-dev
VERSION=$(cat versions.lst | grep ":util-linux:" | awk -F: '{print $3}')
if [ "${VERSION}" == "" ]; then
    echo "  ${YELLOW}Obtaining Current Version${NORMAL}"
    mkdir -p $CUR/tmp; sudo rm $CUR/tmp -fR; mkdir -p $CUR/tmp; cd $CUR/tmp
    wget -q https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/ -O index
    cat index | grep href | grep v | awk -F "v" '{print $2}' | awk -F "/" '{print $1}' > index2
    for V in $(cat index2); do VERSION=$V; done
    echo ":util-linux:${VERSION}" >> $CUR/versions.lst
    cd $CUR; sudo rm tmp -fR
fi
VERSION=$(cat versions.lst | grep ":util-linux:" | awk -F: '{print $3}')

VERSION=2.39.2 ### 2.40.x and above have issues I haven't traced yet

VERS=$(echo $VERSION | awk -F. '{print $1 "." $2}')

if [ ! -d $CUR/src/utillinux-${VERSION} ]; then
    cd $CUR/src
    echo "  ${YELLOW}Obtaining Source Code${NORMAL}"
    wget -q https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v${VERS}/util-linux-${VERSION}.tar.gz || exit 1
    echo "  ${YELLOW}Extracting Source Code${NORMAL}"
    tar -zxf util-linux-${VERSION}.tar.gz
    mv util-linux-${VERSION} utillinux-${VERSION}
    rm util-linux-${VERSION}.tar.gz -f
fi

cd $CUR/src/utillinux-${VERSION}

if [ ! -f ./.configured ]; then
    echo "  ${YELLOW}Configuring source code${NORMAL}"

    test=$(cat /etc/group | grep tty)
    if [ "${test}" == "" ]; then
        cat /etc/group > /tmp/group
        echo "tty:x:5:" >> /tmp/group
        sudo cp /tmp/group /etc/ -f
        sudo rm /tmp/group -f
    fi

    mkdir -pv /var/lib/hwclock
    ./configure ADJTIME_PATH=/var/lib/hwclock/adjtime --libdir=/usr/lib --docdir=/usr/share/doc/util-linux \
        --disable-chfn-chsh --disable-login --disable-nologin --disable-su --disable-setpriv --disable-runuser \
        --disable-pylibmount --disable-static --without-python runstatedir=/run >./.configured.log 2>&1 || exit 1
    touch ./.configured
fi

if [ ! -f ./.compiled ]; then
    echo "  ${YELLOW}Compiling source code${NORMAL}"
    make -j$(nproc) >./.compiled.log 2>&1 || exit 1
    touch ./.compiled
fi

if [ ! -d $CUR/bin/utillinux-${VERSION} ]; then
    echo "  ${YELLOW}Installing source code${NORMAL}"
    make DESTDIR=$CUR/bin/utillinux-${VERSION} install >./.installed.log 2>&1
fi

cd $CUR/bin/utillinux-${VERSION}/usr/lib
sudo rm *.la >/dev/null 2>&1
