#!/bin/sh
clear; CUR=$(pwd); OLD=$CUR; . /etc/init.d/tc-functions; . ../functions;       ##### TCL
TITLE="
${CYAN}        ######
${CYAN}       ##    ## ####
${CYAN}       ##        ##  ##     ##
${CYAN}        ######   ##  ###   ### ########
${CYAN}             ##  ##  #### #### ##     ## ##
${CYAN}       ##    ##  ##  ## ### ## ##     ## ##       ########
${CYAN}        ######   ##  ##     ## ########  ##       ##
${CYAN}                #### ##     ## ##        ##       ##             ${WHITE}#####
${CYAN}                     ##     ## ##        ##       ######        ${WHITE}##   ##
${CYAN}                   #           ##        ##       ##            ${WHITE}# ${BLUE}0 0 ${WHITE}#
${CYAN}  ######          ###                    ######## ##           ${WHITE}#   ${YELLOW}V   ${WHITE}#
${CYAN}    ##             #                              ########    ${WHITE}##       ##
${CYAN}    ##         ###    ### ####   ###    ###  ##### #####     ${WHITE}#           #
${CYAN}    ##        #  ##    ###    ##  ##     ##    ##   ##      ${WHITE}#             #
${CYAN}    ##       #   ##    ##     ##  ##     ##      ###        ${WHITE}#  #       #  #
${CYAN}    ##          ###    ##     ##  ##     ##      ###       ${YELLOW}@@${WHITE}##         ##${YELLOW}@@
${CYAN}    ##       # ###     ##     ##  ##     ##     ## ##    ${YELLOW}@@@@@@${WHITE}#       #${YELLOW}@@@@@@
${CYAN}    ##      ## ### #   ##     ##  ###   ###    ##   ##   ${YELLOW}@@@@@@@${WHITE}# ${RED}CDC ${WHITE}#${YELLOW}@@@@@@@
${CYAN}  ############  ###   ####   ####   #### ### ##### #####   ${YELLOW}@@@@@${WHITE} ##### ${YELLOW}@@@@@"
#------------------------------------------------------------------------------#
# This file is a part of a project which contains pieces from other projects   #
# belonging to potentially hundreds of individuals globally in an effort to    #
# bring together some of the best computing materials the world has to offer   #
# under a single roof with an automated core allowing a tailor-made experience #
# like no other. Some of these pieces may have originated from individuals,    #
# while others may have come from public distributions such as Alpine, Apache, #
# CentOS, Debian, Fedora, SlackWare, TinyCore, Zorin, etc. just to name a few. #
# This project will be ever changing throughout the entire Version 0.x.x life- #
# cycle and should NOT be considered a complete and/or functional system.      #
#------------------------------------------------------------------------------#
echo "${TITLE}${NORMAL}"; echo; SFX=$(GetProcessorType)
SXX=${SFX/x86_/x}; export CFLAGS CXXFLAGS LDFLAGS

# This script is the first step of creating a core system using TCL's 14x as our base
# We're probably going to need x86, x64 and all three ARM architectures separately so
# we might as well do them all in one pass to save time and effort.

HOST="$(cat /opt/tcemirror)/14.x"

echo -n "${YELLOW}Loading Support Extensions:${NORMAL}"
EXTS="util-linux"
ExtLoad $EXTS


PLATS="x86"
for PLAT in $PLATS
do
    if [ ! -d $CUR/$PLAT ]; then
        mkdir -p $CUR/$PLAT
        cd $CUR/$PLAT
        wget -q $HOST/$PLAT/release/distribution_files/rootfs.gz
        [ ! -f rootfs.gz ] && exit 1
        zcat rootfs.gz | sudo cpio -i -H newc -d >/dev/null 2>&1
        rm rootfs.gz -f
    fi
done
### DONE ###



PLATS="x86_64"
for PLAT in $PLATS
do
    if [ ! -d $CUR/$PLAT ]; then
        mkdir -p $CUR/$PLAT
        cd $CUR/$PLAT
        wget -q $HOST/$PLAT/release/distribution_files/rootfs64.gz
        [ ! -f rootfs64.gz ] && exit 1
        zcat rootfs64.gz | sudo cpio -i -H newc -d >/dev/null 2>&1
        rm rootfs64.gz -f
    fi
done
### DONE ###



PLATS="armv6 armv7"
for PLAT in $PLATS
do
    if [ ! -d $CUR/$PLAT ]; then
        mkdir -p $CUR/$PLAT
        cd $CUR/$PLAT
        wget -q ${HOST}/${PLAT}/releases/RPi/piCore-14.1.0.zip
        [ ! -f piCore-14.1.0.zip ] && exit 1
        unzip piCore-14.1.0.zip >/dev/null 2>&1
        rm piCore-14.1.0.zip -f

        Sectors=$(fdisk -l piCore-14.1.0.img | grep piCore-14.1.0.img1 | awk '{print $4}')
        Offset=$(expr 512 \* 8192)
        Sizemax=$(expr 512 \* $Sectors)
        mkdir TMP
        sudo mount -o loop,offset=${Offset},sizelimit=${Sizemax} piCore-14.1.0.img TMP
        cp TMP/rootfs*.gz ./
        sudo umount TMP

        sudo rm TMP piCore* -fR
        zcat rootfs-piCore-14.1.gz | sudo cpio -i -H newc -d >/dev/null 2>&1
        rm rootfs-piCore-14.1.gz -f
    fi
done

PLATS="aarch64"
for PLAT in $PLATS
do
    if [ ! -d $CUR/$PLAT ]; then
        mkdir -p $CUR/$PLAT
        cd $CUR/$PLAT
        wget -q ${HOST}/${PLAT}/releases/RPi/piCore64-14.1.0.zip
        [ ! -f piCore64-14.1.0.zip ] && exit 1
        unzip piCore64-14.1.0.zip >/dev/null 2>&1
        rm piCore64-14.1.0.zip -f

        Sectors=$(fdisk -l piCore64-14.1.0.img | grep piCore64-14.1.0.img1 | awk '{print $4}')
        Offset=$(expr 512 \* 8192)
        Sizemax=$(expr 512 \* $Sectors)
        mkdir TMP
        sudo mount -o loop,offset=${Offset},sizelimit=${Sizemax} piCore64-14.1.0.img TMP
        cp TMP/rootfs*.gz ./
        sudo umount TMP

        sudo rm TMP piCore* -fR
        zcat rootfs-piCore64-14.1.gz | sudo cpio -i -H newc -d >/dev/null 2>&1
        rm rootfs-piCore64-14.1.gz -f

    fi
done

