#!/bin/sh

#########################
## APPLICATION DETAILS ##
################################################################################
pkgname=chrpath
pkgver=0.16
pkgrel=4
pkgdesc="Modify rpath of compiled programs"
url="https://tracker.debian.org/pkg/chrpath"
arch="all"
license="GPL2"
source="https://alioth-archive.debian.org/releases/chrpath/chrpath/$pkgver/chrpath-$pkgver.tar.gz"
pkgfile="${pkgname}-${pkgver}.tar.gz"
pkgdir="${pkgname}-${pkgver}"
################################################################################

########################
# Extension Maintainer #
################################################################################
pkg_maintainer="CentralWare Development Centers"
pkg_maint_contact=""
################################################################################

get_source()
{
    echo "Getting current version information..."
    [ "${pkgver}" == "" ] && get_version

    if [ ! -f $CUR/src/${pkgfile} ]; then
        echo "Download SOURCE TARBALL from website (${pkgver})"
        mkdir -p $CUR/src/raw; cd $CUR/src
        wget -q --no-check-certificate $source
    fi

    if [ ! -d $CUR/src/${pkgdir} ]; then
        cd $CUR/src
        tar -zxf ${pkgfile}
        if [ ! -d $CUR/src/raw/${pkgdir} ]; then
            cp $CUR/src/${pkgdir} $CUR/src/raw/ -R
        fi
    fi
}

src_build()
{
    get_source
    [ ! -d $CUR/src/${pkgdir} ] && $(echo "${RED}ERROR! ${MAGENTA}Cannot find working source directory!"; exit 1)

    cd $CUR/src/${pkgdir}
    if [ ! -f ./.configured ]; then
        echo "${CYAN}Configuring...${NORMAL}"
        CPU=$(GetProcessorType)
        ./configure \
            --prefix=/usr/local \
            --sysconfdir=/usr/local/etc \
            --mandir=/usr/local/share/man \
            --infodir=/usr/local/share/info \
            --localstatedir=/var > \
            $CUR/_configure.log 2>&1 || exit 1
        touch ./.configured
    fi
    echo "${CYAN}Compiling...${NORMAL}"
    make -j$(nproc) > $CUR/_compile.log 2>&1 || exit 1

    echo "${CYAN}Testing...${NORMAL}"
    make -j$(nproc) check > $CUR/_testing.log 2>&1 || exit 1

    echo "${CYAN}Preparing...${NORMAL}"
    DOC="docdir=/usr/local/share/doc/$pkgname-$pkgver"
    make DESTDIR=$CUR/ext $DOC install > $CUR/_install.log 2>&1 || exit 1

}



##>> SHARED FUNCTIONS (Update to shared location)
. ../functions

CPU=$(GetProcessorType)

clear
CUR=$(pwd)
ShowTitle
echo
echo "${WHITE}Extension ${GREEN}${pkgname}${NORMAL}"
echo

ExtClean
ExtLoadQuiet compiling wget bash python3.6

src_build


#package() {
#    make DESTDIR="$pkgdir" docdir=/usr/share/doc/$pkgname-$pkgver install
#}
