#!/bin/sh

#########################
## APPLICATION DETAILS ##
################################################################################
# Maintainer: Leonardo Arena <rnalrd@alpinelinux.org>
pkgname=diffutils
pkgver=3.10
pkgrel=0
pkgdesc="Show differences among files"
subpackages="$pkgname-doc"
url="https://www.gnu.org/software/diffutils/"
arch="all"
license="GPL-3.0-or-later"
checkdepends="perl"
source="https://ftp.gnu.org/pub/gnu/diffutils/diffutils-$pkgver.tar.xz"
pkgfile="diffutils-$pkgver.tar.xz"
pkgdir="diffutils-$pkgver"
################################################################################

########################
# Extension Maintainer #
################################################################################
pkg_maintainer="CentralWare Development Centers"
pkg_maint_contact=""
################################################################################

get_source()
{
    if [ ! -f $CUR/src/${pkgfile} ]; then
        echo "Download SOURCE TARBALL from website"
        mkdir -p $CUR/src/raw; cd $CUR/src
        wget -q --no-check-certificate $source
    fi

    if [ ! -d $CUR/src/${pkgdir} ]; then
        cd $CUR/src
        tar -xf ${pkgfile}
        if [ ! -d $CUR/src/raw/${pkgdir} ]; then
            cp $CUR/src/${pkgdir} $CUR/src/raw/ -R
        fi
    fi
}

src_depends()
{
    echo "Loading compilation dependencies"
}

src_build()
{
    get_source
    [ ! -d $CUR/src/${pkgdir} ] && $(echo "${RED}ERROR! ${MAGENTA}Cannot find working source directory!"; exit 1)

    cd $CUR/src/${pkgdir}
    if [ ! -f ./.configured ]; then
        echo "${CYAN}Configuring...${NORMAL}"
        CPU=$(GetProcessorType)
        ./configure \
            --prefix=/usr/local \
            --mandir=/usr/local/share/man \
            --infodir=/usr/local/share/info \
            --disable-nls > \
            $CUR/_configure.log 2>&1 || exit 1
        touch ./.configured
    fi
    echo "${CYAN}Compiling...${NORMAL}"
    make -j$(nproc) > $CUR/_compile.log 2>&1 || exit 1

    echo "${CYAN}Testing...${NORMAL}"
    make -j$(nproc) check > $CUR/_testing.log 2>&1 || exit 1

    echo "${CYAN}Preparing...${NORMAL}"
    make DESTDIR=$CUR/ext install > $CUR/_install.log 2>&1 || exit 1

}



##>> SHARED FUNCTIONS (Update to shared location)
. ../functions

CPU=$(GetProcessorType)

clear
CUR=$(pwd)
ShowTitle
echo
echo "${WHITE}Extension ${GREEN}${pkgname}${NORMAL}"
echo

ExtClean
ExtLoadQuiet compiling less wget perl5

src_build


