#!/bin/sh
clear; CUR=$(pwd); OLD=$CUR; . /etc/init.d/tc-functions; . ../functions;       ##### TCL
TITLE="
${CYAN}        ######
${CYAN}       ##    ## ####
${CYAN}       ##        ##  ##     ##
${CYAN}        ######   ##  ###   ### ########
${CYAN}             ##  ##  #### #### ##     ## ##
${CYAN}       ##    ##  ##  ## ### ## ##     ## ##       ########
${CYAN}        ######   ##  ##     ## ########  ##       ##
${CYAN}                #### ##     ## ##        ##       ##             ${WHITE}#####
${CYAN}                     ##     ## ##        ##       ######        ${WHITE}##   ##
${CYAN}                   #           ##        ##       ##            ${WHITE}# ${BLUE}0 0 ${WHITE}#
${CYAN}  ######          ###                    ######## ##           ${WHITE}#   ${YELLOW}V   ${WHITE}#
${CYAN}    ##             #                              ########    ${WHITE}##       ##
${CYAN}    ##         ###    ### ####   ###    ###  ##### #####     ${WHITE}#           #
${CYAN}    ##        #  ##    ###    ##  ##     ##    ##   ##      ${WHITE}#             #
${CYAN}    ##       #   ##    ##     ##  ##     ##      ###        ${WHITE}#  #       #  #
${CYAN}    ##          ###    ##     ##  ##     ##      ###       ${YELLOW}@@${WHITE}##         ##${YELLOW}@@
${CYAN}    ##       # ###     ##     ##  ##     ##     ## ##    ${YELLOW}@@@@@@${WHITE}#       #${YELLOW}@@@@@@
${CYAN}    ##      ## ### #   ##     ##  ###   ###    ##   ##   ${YELLOW}@@@@@@@${WHITE}# ${RED}CDC ${WHITE}#${YELLOW}@@@@@@@
${CYAN}  ############  ###   ####   ####   #### ### ##### #####   ${YELLOW}@@@@@${WHITE} ##### ${YELLOW}@@@@@"
#------------------------------------------------------------------------------#
# This file is a part of a project which contains pieces from other projects   #
# belonging to potentially hundreds of individuals globally in an effort to    #
# bring together some of the best computing materials the world has to offer   #
# under a single roof with an automated core allowing a tailor-made experience #
# like no other. Some of these pieces may have originated from individuals,    #
# while others may have come from public distributions such as Alpine, Apache, #
# CentOS, Debian, Fedora, SlackWare, TinyCore, Zorin, etc. just to name a few. #
# This project will be ever changing throughout the entire Version 0.x.x life- #
# cycle and should NOT be considered a complete and/or functional system.      #
#------------------------------------------------------------------------------#
echo "${TITLE}${NORMAL}"; echo; SFX=$(GetProcessorType)
SXX=${SFX/x86_/x}; export CFLAGS CXXFLAGS LDFLAGS

echo -n "${CYAN}Loading support extensions:${NORMAL}"
ExtClean
ExtLoad wget git; echo

cd $CUR; mkdir -p $CUR/bin $CUR/src
[ ! -f $CUR/versions.lst ] && touch $CUR/versions.lst


















###############
## e2fsprogs ##
###############
INCLUDE_e2fsprogs=1
if [ $INCLUDE_e2fsprogs -gt 0 ]; then
    cd $CUR; echo "${CYAN}Package ${GREEN}e2fsprogs${NORMAL}"
    echo -n "${CYAN}Loading support extensions:${NORMAL}"
    ExtLoad compiletc
    VERSION=$(cat versions.lst | grep ":e2fsprogs:" | awk -F: '{print $3}')
    if [ "${VERSION}" == "" ]; then
        echo "  ${YELLOW}Obtaining Current Version${NORMAL}"
        mkdir -p $CUR/tmp; sudo rm $CUR/tmp -fR; mkdir -p $CUR/tmp; cd $CUR/tmp
        wget -q https://raw.githubusercontent.com/tytso/e2fsprogs/refs/heads/master/version.h
        TMP=$(cat version.h | grep E2FSPROGS_VERSION | awk '{print $3}'); TMP=${TMP//\"/}
        VERSION=$TMP; echo ":e2fsprogs:${VERSION}" >> $CUR/versions.lst; cd $CUR; sudo rm tmp -fR
    fi
    VERSION=$(cat versions.lst | grep ":e2fsprogs:" | awk -F: '{print $3}')
    if [ ! -d src/e2fsprogs-${VERSION} ]; then
        echo "  ${YELLOW}Obtaining Source Code${NORMAL}"
        wget -q https://github.com/tytso/e2fsprogs/archive/refs/tags/v${VERSION}.zip
        unzip v${VERSION}.zip > /dev/null 2>&1
        rm v${VERSION}.zip -f
        mv e2fsprogs-${VERSION} $CUR/src/
    fi
    cd $CUR/src/e2fsprogs-${VERSION}
    if [ ! -f ./.configured ]; then
        echo "  ${YELLOW}Configuring source code${NORMAL}"
        time ./configure > ./.configured.log 2>&1  || exit 1
        touch ./.configured
    fi
    if [ ! -f ./.compiled ]; then
        echo "  ${YELLOW}Compiling source code${NORMAL}"
        time make -j$(nproc) > ./.compiled.log 2>&1 || exit 1
        touch ./.compiled
    fi
    if [ ! -d $CUR/bin/e2fsprogs-${VERSION} ]; then
        echo "  ${YELLOW}Installing compiled code${NORMAL}"
        make DESTDIR=/tmp/packager/e2fsprogs-${VERSION} install > ./.installed.log 2>&1 || exit 1
        sudo mv /tmp/packager/e2fsprogs-${VERSION} $CUR/bin/
    fi
    echo
fi



















