#!/bin/sh

PROJECT=/array1/PROJECTS/simpleNIX

# Common ANSI Colors
RED="$(echo -e '\033[1;31m')";       GREEN="$(echo -e '\033[1;32m')"
YELLOW="$(echo -e '\033[1;33m')";    BLUE="$(echo -e '\033[1;34m')"
MAGENTA="$(echo -e '\033[1;35m')";   CYAN="$(echo -e '\033[1;36m')"
WHITE="$(echo -e '\033[1;37m')";     NORMAL="$(echo -e '\033[0;39m')"

# Repository Caches
REPOLIST="
alpine::git:https://git.alpinelinux.org/aports::sources
arch::https://mirror.rackspace.com/archlinux/sources
tiny::http://10.0.0.100/tinycorelinux
tiny::https://distro.ibiblio.org/tinycorelinux
tiny::http://repo.tinycorelinux.net
simple::http://10.0.0.100/simplenix
"

GetRepoCount()
{
    FIND=$1; CNT=0
    [ "${FIND}" == "" ] && FIND="simple"
    for REPO in $REPOLIST
    do
        [ "${FIND}" == "$(echo $REPO | awk -F: '{print $1}')" ] && CNT=$((CNT + 1))
    done
    echo $CNT
}

GetRepo()
{
    FIND=$1; FIELD=$2; INDEX=$3
    [ "${FIND}" == "" ] && FIND="simple"
    [ "${FIELD}" == "" ] && FIELD=2
    [ "${INDEX}" == "" ] && INDEX=1
    CNT=0
    for REPO in $REPOLIST
    do
        if [ ! "${REPO}" == "" ]; then
            if [ "${FIND}" == "$(echo $REPO | awk -F: '{print $1}')" ]; then
                CNT=$((CNT + 1))
                if [ ${CNT} -eq $INDEX ]; then
                    case $FIELD in
                        1) echo "${REPO}" | awk -F "::" '{print $1}' ;;
                        2) echo "${REPO}" | awk -F "::" '{print $2}' ;;
                        3) echo "${REPO}" | awk -F "::" '{print $3}' ;;
                        4) echo "${REPO}" | awk -F "::" '{print $4}' ;;
                        *) echo $REPO ;;
                    esac
                fi
            fi
        fi
    done
}

GetVersion()
{
    for i in $@
    do
        case $i in
            *=*)
                case $i in
                    version*)  APP_VER=${i#*=} ;;
                esac
                ;;
        esac
    done
    echo $APP_VER
}

ShowTitle()
{
    echo "${CYAN}        ######"
    echo "${CYAN}       ##    ## ####"
    echo "${CYAN}       ##        ##  ##     ##"
    echo "${CYAN}        ######   ##  ###   ### ########"
    echo "${CYAN}             ##  ##  #### #### ##     ## ##"
    echo "${CYAN}       ##    ##  ##  ## ### ## ##     ## ##       ########"
    echo "${CYAN}        ######   ##  ##     ## ########  ##       ##"
    echo "${CYAN}                #### ##     ## ##        ##       ##             ${WHITE}#####"
    echo "${CYAN}                     ##     ## ##        ##       ######        ${WHITE}##   ##"
    echo "${CYAN}                   ${YELLOW}#${CYAN}           ##        ##       ##            ${WHITE}# ${BLUE}0 0 ${WHITE}#"
    echo "${CYAN}  ######          ${YELLOW}###${CYAN}                    ######## ##           ${WHITE}#   ${YELLOW}V   ${WHITE}#"
    echo "${CYAN}    ##             ${YELLOW}#${CYAN}                              ########    ${WHITE}##       ##"
    echo "${CYAN}    ##         ###    ### ####   ###    ###  ##### #####     ${WHITE}#           #"
    echo "${CYAN}    ##        #  ##    ###    ##  ##     ##    ##   ##      ${WHITE}#             #"
    echo "${CYAN}    ##       #   ###   ##     ##  ##     ##      ###        ${WHITE}#  #       #  #"
    echo "${CYAN}    ##          # #    ##     ##  ##     ##      ###       ${YELLOW}@@${WHITE}##         ##${YELLOW}@@"
    echo "${CYAN}    ##       # ###  #  ##     ##  ##     ##     ## ##    ${YELLOW}@@@@@@${WHITE}#       #${YELLOW}@@@@@@"
    echo "${CYAN}    ##      ## ##  #   ##     ##  ###   ###    ##   ##   ${YELLOW}@@@@@@@${WHITE}#${RED}C D C${WHITE}#${YELLOW}@@@@@@@"
    echo "${CYAN}  ############  ###    ####   ####  #### ### ##### #####   ${YELLOW}@@@@@${WHITE} ##### ${YELLOW}@@@@@"
}

GetProcessorType()
{
    BITS=""; [ ! "$(uname -r | grep 64)" == "" ] && BITS="64"
    CPU=`uname -m`
    case "$CPU" in
        i686)
            CFLAGS="$FLTO -fuse-linker-plugin -march=i486 -mtune=i686 $OPTIMIZE $SYMBOLS $DEFINES -pipe -Wall -Wextra -fno-plt"
            CXXFLAGS="$FLTO -fuse-linker-plugin -march=i486 -mtune=i686 $OPTIMIZE $SYMBOLS -pipe -Wall -Wextra -fno-exceptions -fno-rtti"
            LDFLAGS="-Wl,-T/usr/local/lib/ldscripts/elf_i386.xbn"
            ;;

        x86_64)
            CFLAGS="$FLTO -fuse-linker-plugin -mtune=generic $OPTIMIZE $SYMBOLS $DEFINES -pipe -Wall -Wextra -fno-plt"
            CXXFLAGS="$FLTO -fuse-linker-plugin -mtune=generic $OPTIMIZE $SYMBOLS -pipe -Wall -Wextra -fno-exceptions -fno-rtti"
            LDFLAGS="-Wl,-T/usr/local/lib/ldscripts/elf_x86_64.xbn"
            ;;

        armv*)
            CFLAGS="-march=armv6zk -mtune=arm1176jzf-s -mfpu=vfp $OPTIMIZE $SYMBOLS $DEFINES -pipe -Wall -Wextra"
            CXXFLAGS="-march=armv6zk -mtune=arm1176jzf-s -mfpu=vfp $OPTIMIZE $SYMBOLS -pipe -Wall -Wextra -fno-exceptions -fno-rtti"
            LDFLAGS="-Wl,-O1"
            ;;

        aarch64)
            CFLAGS="-march=armv8-a+crc -mtune=cortex-a72 $OPTIMIZE $SYMBOLS $DEFINES -pipe -Wall -Wextra"
            CXXFLAGS="-march=armv8-a+crc -mtune=cortex-a72 $OPTIMIZE $SYMBOLS -pipe -Wall -Wextra -fno-exceptions -fno-rtti"
            LDFLAGS="-Wl,-O1"
            ;;

        *)
            echo "$PROCESSOR_TYPE: Unknown processor type. Please add an entry for it in this script."
            exit
            ;;
    esac
    export CPU BITS CFLAGS CXXFLAGS LDFLAGS
}

nproc()
{
    LARGE=0
    ITEMS=$(cat /proc/cpuinfo | grep "processor" | grep ":" | awk -F: '{print $2}')
    for ITEM in $ITEMS
    do
        [ $ITEM -gt $LARGE ] && LARGE=$ITEM
    done
    LARGE=$(expr $LARGE + 1) 2>/dev/null
    echo $LARGE
}






##################
## COMMAND LINE: #
####################################################
# exts -d [EXT LIST] (Download extension from REPO)
# exts -l [EXT LIST] (Load DOWNLOADED extension)
# exts -i [EXT LIST] (Download, Load and Install)

exts()
{
    CMD=$1; EXTS=${@/$1/}

    if [ "${CMD}" == "wipe" ]; then
        cd /tmp/tcloop
        sudo umount * >/dev/null 2>&1
        sudo rmdir * >/dev/null 2>&1
        cd /usr/local/tce.installed
        sudo rm * >/dev/null 2>&1
    else
#        echo "Loading extensions: [${EXTS}]"
        for EXT in $EXTS
        do
            EXT=${EXT//.tcz/}
            case $CMD in
                -t)
                    if [ ! -f /etc/sysconfig/tcedir/optional/${EXT}.tcz ]; then
#                        echo "Downloading Extension $EXT"
                        su -c "tce-load -w ${EXT} >/dev/null 2>&1 || exit 1" tc
                    fi
                    if [ ! -f /tmp/tcloop/${EXT} ]; then
#                        echo "Loading Extension $EXT"
                        su -c "tce-load -i ${EXT} >/dev/null 2>&1 || exit 1" tc
                    fi
                    ;;
                -d)
                    if [ ! -f /etc/sysconfig/tcedir/optional/${EXT}.tcz ]; then
#                        echo "Downloading Extension $EXT"
                        su -c "tce-load -w ${EXT} >/dev/null 2>&1 || exit 1" tc
                    fi
                    ;;
                -l)
                    if [ ! -f /tmp/tcloop/${EXT} ]; then
#                        echo "Loading Extension $EXT"
                        su -c "tce-load -i ${EXT} >/dev/null 2>&1 || exit 1" tc
                    fi
                    ;;
                -i)
#                    echo "Installing Extension $EXT"
                    su -c "tce-load -wi ${EXT} >/dev/null 2>&1 || exit 1" tc
                    ;;
                *)  echo "${RED}UNKNOWN COMMAND ${YELLOW}${CMD}${NORMAL}"
                    exit 1
                    ;;
            esac
        done
    fi

}





ExtClean()
{
    exts wipe
}
ExtLoad()
{
    echo -n "${CYAN}Loading support extensions:${NORMAL}"
    for EXT in $@
    do
        echo -n " ${YELLOW}$EXT${NORMAL}"
        exts -t $EXT
    done
    echo
}
ExtLoadQuiet()
{
    for EXT in $@
    do
        exts -t $EXT
    done
}

doroot()
{
    [ ! "$(whoami)" == "root" ] && echo "Run as root" && exit 1
}

noroot()
{
    [ "$(whoami)" == "root" ] && echo "Do not run as root" && exit 1
}


#echo "REPOS : $(GetRepoCount)"
#echo "SERVER: $(GetRepo)"get_version()

