#!/bin/sh

CRE="$(echo -e '\r\033[K')"
RED="$(echo -e '\033[1;31m')"
GREEN="$(echo -e '\033[1;32m')"
YELLOW="$(echo -e '\033[1;33m')"
BLUE="$(echo -e '\033[1;34m')"
MAGENTA="$(echo -e '\033[1;35m')"
CYAN="$(echo -e '\033[1;36m')"
WHITE="$(echo -e '\033[1;37m')"
NORMAL="$(echo -e '\033[0;39m')"

GetProcessorType()
{
    PROCESSOR_TYPE=`uname -m`
    echo "$PROCESSOR_TYPE"

    case "$PROCESSOR_TYPE" in
        i686)
            CFLAGS="$FLTO -fuse-linker-plugin -march=i486 -mtune=i686 $OPTIMIZE $SYMBOLS $DEFINES -pipe -Wall -Wextra -fno-plt"
            CXXFLAGS="$FLTO -fuse-linker-plugin -march=i486 -mtune=i686 $OPTIMIZE $SYMBOLS -pipe -Wall -Wextra -fno-exceptions -fno-rtti"
            LDFLAGS="-Wl,-T/usr/local/lib/ldscripts/elf_i386.xbn"
            ;;

        x86_64)
            CFLAGS="$FLTO -fuse-linker-plugin -mtune=generic $OPTIMIZE $SYMBOLS $DEFINES -pipe -Wall -Wextra -fno-plt"
            CXXFLAGS="$FLTO -fuse-linker-plugin -mtune=generic $OPTIMIZE $SYMBOLS -pipe -Wall -Wextra -fno-exceptions -fno-rtti"
            LDFLAGS="-Wl,-T/usr/local/lib/ldscripts/elf_x86_64.xbn"
            ;;

        armv*)
            CFLAGS="-march=armv6zk -mtune=arm1176jzf-s -mfpu=vfp $OPTIMIZE $SYMBOLS $DEFINES -pipe -Wall -Wextra"
            CXXFLAGS="-march=armv6zk -mtune=arm1176jzf-s -mfpu=vfp $OPTIMIZE $SYMBOLS -pipe -Wall -Wextra -fno-exceptions -fno-rtti"
            LDFLAGS="-Wl,-O1"
            ;;

        aarch64)
            CFLAGS="-march=armv8-a+crc -mtune=cortex-a72 $OPTIMIZE $SYMBOLS $DEFINES -pipe -Wall -Wextra"
            CXXFLAGS="-march=armv8-a+crc -mtune=cortex-a72 $OPTIMIZE $SYMBOLS -pipe -Wall -Wextra -fno-exceptions -fno-rtti"
            LDFLAGS="-Wl,-O1"
            ;;

        *)
            echo "$PROCESSOR_TYPE: Unknown processor type. Please add an entry for it in this script."
            exit
            ;;
    esac
}

ExtClean()
{
    cd /tmp/tcloop
    sudo umount * >/dev/null 2>&1
    sudo rmdir * >/dev/null 2>&1
    sudo rm /usr/local/tce.installed/*
}
ExtLoad()
{
    for EXT in $@
    do
        EXT=${EXT/.tcz/}
        echo -n " ${YELLOW}${EXT}${NORMAL}"
        [ ! -f /etc/sysconfig/tcedir/optional/${EXT}.tcz ] && su -c "tce-load -w ${EXT} >/dev/null 2>&1 || exit 1" tc
        [ ! -d /tmp/tcloop/${EXT} ] && su -c "tce-load -i ${EXT} >/dev/null 2>&1 || exit 1" tc
    done
    echo
}
ExtLoadQuiet()
{
    for EXT in $@
    do
        EXT=${EXT/.tcz/}
        [ ! -f /etc/sysconfig/tcedir/optional/${EXT}.tcz ] && su -c "tce-load -w ${EXT} > /dev/null 2>&1 || exit 1" tc
        [ ! -d /tmp/tcloop/${EXT} ] && su -c "tce-load -i ${EXT} > /dev/null 2>&1 || exit 1" tc
    done
}
