#!/bin/sh

#########################
## APPLICATION DETAILS ##
################################################################################
# Maintainer: Natanael Copa <ncopa@alpinelinux.org>
pkgname=cppunit
pkgver=1.15.1
pkgrel=4
pkgdesc="C++ unit testing framework"
url="https://www.freedesktop.org/wiki/Software/cppunit/"
arch="all"
license="LGPL2"
source="https://dev-www.libreoffice.org/src/cppunit-$pkgver.tar.gz"
pkgfile="${pkgname}-${pkgver}.tar.gz"
pkgdir="${pkgname}-${pkgver}"
################################################################################

########################
# Extension Maintainer #
################################################################################
pkg_maintainer="CentralWare Development Centers"
pkg_maint_contact=""
################################################################################

get_source()
{
    echo "Getting current version information..."
    [ "${pkgver}" == "" ] && get_version

    if [ ! -f $CUR/src/${pkgfile} ]; then
        echo "Download SOURCE TARBALL from website (${pkgver})"
        mkdir -p $CUR/src/raw; cd $CUR/src
        wget -q --no-check-certificate $source
    fi

    if [ ! -d $CUR/src/${pkgdir} ]; then
        cd $CUR/src
        tar -zxf ${pkgfile}
        if [ ! -d $CUR/src/raw/${pkgdir} ]; then
            cp $CUR/src/${pkgdir} $CUR/src/raw/ -R
        fi
    fi
}

src_depends()
{
    echo "Loading compilation dependencies"
}

src_build()
{
    get_source
    [ ! -d $CUR/src/${pkgdir} ] && $(echo "${RED}ERROR! ${MAGENTA}Cannot find working source directory!"; exit 1)

    cd $CUR/src/${pkgdir}
    if [ ! -f ./.configured ]; then
        echo "${CYAN}Configuring...${NORMAL}"
        CPU=$(GetProcessorType)
        LIBS="-ldl" ./configure \
            --prefix=/usr/local \
            --sysconfdir=/usr/local/etc \
            --mandir=/usr/local/share/man \
            --infodir=/usr/local/share/info \
            --localstatedir=/var > \
            $CUR/_configure.log 2>&1 || exit 1
        touch ./.configured
    fi
    echo "${CYAN}Compiling...${NORMAL}"
    make -j$(nproc) > $CUR/_compile.log 2>&1 || exit 1

    echo "${CYAN}Testing...${NORMAL}"
    make -j$(nproc) check > $CUR/_testing.log 2>&1 || exit 1

    echo "${CYAN}Preparing...${NORMAL}"
    make DESTDIR=$CUR/ext install > $CUR/_install.log 2>&1 || exit 1
}



##>> SHARED FUNCTIONS (Update to shared location)
. ../functions

CPU=$(GetProcessorType)

clear
CUR=$(pwd)
ShowTitle
echo
echo "${WHITE}Extension ${GREEN}${pkgname}${NORMAL}"
echo

ExtClean
ExtLoadQuiet compiling wget

src_build
