#!/bin/sh

#########################
## APPLICATION DETAILS ##
################################################################################
pkgname=b43-fwcutter
pkgver=019
pkgrel=3
pkgdesc="Tool to extract firmware from Broadcom drivers"
url="https://wireless.wiki.kernel.org/en/users/Drivers/b43"
arch="all"
license="BSD-2-Clause"
source="http://bues.ch/b43/fwcutter/b43-fwcutter-$pkgver.tar.bz2"
pkgfile="b43-fwcutter-$pkgver.tar.bz2"
pkgdir="${pkgname}-${pkgver}"
################################################################################

########################
# Extension Maintainer #
################################################################################
pkg_maintainer="CentralWare Development Centers"
pkg_maint_contact=""
################################################################################

get_source()
{
    echo "Getting current version information..."
    [ "${pkgver}" == "" ] && get_version

    if [ ! -f $CUR/src/${pkgfile} ]; then
        echo "Download SOURCE TARBALL from website (${pkgver})"
        mkdir -p $CUR/src/raw; cd $CUR/src
        wget -q --no-check-certificate $source
    fi

    if [ ! -d $CUR/src/${pkgdir} ]; then
        cd $CUR/src
        tar -jxf ${pkgfile}
        if [ ! -d $CUR/src/raw/${pkgdir} ]; then
            cp $CUR/src/${pkgdir} $CUR/src/raw/ -R
        fi
    fi
}

src_build()
{
    get_source
    [ ! -d $CUR/src/${pkgdir} ] && $(echo "${RED}ERROR! ${MAGENTA}Cannot find working source directory!"; exit 1)

    cd $CUR/src/${pkgdir}

    echo "${CYAN}Compiling...${NORMAL}"
    make -j$(nproc) > $CUR/_compile.log 2>&1 || exit 1

    echo "${CYAN}Preparing...${NORMAL}"
    sudo make PREFIX=$CUR/ext/usr/local install > $CUR/_install.log 2>&1 || exit 1
    sudo mkdir -p $CUR/ext/usr/local/share/
    cd ${CUR}/ext/usr/local
    sudo mv man $CUR/ext/usr/local/share/
    sudo chown tc:staff $CUR/ext -fR
}



##>> SHARED FUNCTIONS (Update to shared location)
. ../functions

CPU=$(GetProcessorType)

clear
CUR=$(pwd)
ShowTitle
echo
echo "${WHITE}Extension ${GREEN}${pkgname}${NORMAL}"
echo

ExtClean
ExtLoadQuiet compiling wget

src_build

