#!/bin/sh
clear; CUR=$(pwd); OLD=$CUR; . /etc/init.d/tc-functions; . ../functions;       ##### TCL
TITLE="
${CYAN}        ######
${CYAN}       ##    ## ####
${CYAN}       ##        ##  ##     ##
${CYAN}        ######   ##  ###   ### ########
${CYAN}             ##  ##  #### #### ##     ## ##
${CYAN}       ##    ##  ##  ## ### ## ##     ## ##       ########
${CYAN}        ######   ##  ##     ## ########  ##       ##
${CYAN}                #### ##     ## ##        ##       ##             ${WHITE}#####
${CYAN}                     ##     ## ##        ##       ######        ${WHITE}##   ##
${CYAN}                   #           ##        ##       ##            ${WHITE}# ${BLUE}0 0 ${WHITE}#
${CYAN}  ######          ###                    ######## ##           ${WHITE}#   ${YELLOW}V   ${WHITE}#
${CYAN}    ##             #                              ########    ${WHITE}##       ##
${CYAN}    ##         ###    ### ####   ###    ###  ##### #####     ${WHITE}#           #
${CYAN}    ##        #  ##    ###    ##  ##     ##    ##   ##      ${WHITE}#             #
${CYAN}    ##       #   ##    ##     ##  ##     ##      ###        ${WHITE}#  #       #  #
${CYAN}    ##          ###    ##     ##  ##     ##      ###       ${YELLOW}@@${WHITE}##         ##${YELLOW}@@
${CYAN}    ##       # ###     ##     ##  ##     ##     ## ##    ${YELLOW}@@@@@@${WHITE}#       #${YELLOW}@@@@@@
${CYAN}    ##      ## ### #   ##     ##  ###   ###    ##   ##   ${YELLOW}@@@@@@@${WHITE}# ${RED}CDC ${WHITE}#${YELLOW}@@@@@@@
${CYAN}  ############  ###   ####   ####   #### ### ##### #####   ${YELLOW}@@@@@${WHITE} ##### ${YELLOW}@@@@@"
#------------------------------------------------------------------------------#
# This file is a part of a project which contains pieces from other projects   #
# belonging to potentially hundreds of individuals globally in an effort to    #
# bring together some of the best computing materials the world has to offer   #
# under a single roof with an automated core allowing a tailor-made experience #
# like no other. Some of these pieces may have originated from individuals,    #
# while others may have come from public distributions such as Alpine, Apache, #
# CentOS, Debian, Fedora, SlackWare, TinyCore, Zorin, etc. just to name a few. #
# This project will be ever changing throughout the entire Version 0.x.x life- #
# cycle and should NOT be considered a complete and/or functional system.      #
#------------------------------------------------------------------------------#
echo "${TITLE}${NORMAL}"; echo; SFX=$(GetProcessorType)
SXX=${SFX/x86_/x}; export CFLAGS CXXFLAGS LDFLAGS

echo -n "${CYAN}Loading support extensions:${NORMAL}"
ExtClean
ExtLoad wget; echo

cd $CUR; mkdir -p $CUR/bin $CUR/src
[ ! -f $CUR/versions.lst ] && touch $CUR/versions.lst


















##########
## perl ##
##########
cd $CUR; echo "${CYAN}Package ${GREEN}perl${NORMAL}"
echo -n "${CYAN}Loading support extensions:${NORMAL}"
ExtLoad compiletc wget

VERSION=$(cat versions.lst | grep ":perl:" | awk -F: '{print $3}')
if [ "${VERSION}" == "" ]; then
    echo "  ${YELLOW}Obtaining current release${NORMAL}"
    mkdir tmp; cd tmp
    [ ! -f index ] && wget -q https://www.perl.org/get.html -O index
    cat index | grep currently | grep stable | awk -F "currently" '{print $2}' | awk '{print $1}' > version
    VERSION=$(cat version | awk -F. '{print $1 "." $2 "." $3}')
    echo ":perl:${VERSION}" >> $CUR/versions.lst
    cd $CUR; sudo rm tmp -fR
fi

VERSION=$(cat versions.lst | grep ":perl:" | awk -F: '{print $3}')

VERSION="5.36.0"

VERS=$(echo $VERSION | awk -F. '{print $1 "." $2}')
VER=$(echo $VERSION | awk -F. '{print $1}')
if [ ! -d $CUR/src/perl-${VERSION} ]; then
    cd $CUR/src; echo "  Downloading source code [${VERSION}]"
    wget -q https://www.cpan.org/src/${VER}.0/perl-${VERSION}.tar.gz
    tar -zxf perl-${VERSION}.tar.gz
    rm perl-${VERSION}.tar.gz -f
fi

cd $CUR/src/perl-${VERSION}
if [ ! -f ./.configured ]; then
    echo "  ${YELLOW}Configuring PERL ${CYAN}${VERS}${NORMAL}"
    ./Configure -des -Dprefix=/usr -Dvendorprefix=/usr -Dprivlib=/usr/lib/perl${VER}/${VERS}/core_perl \
        -Darchlib=/usr/lib/perl${VER}/${VERS}/core_perl -Dsitelib=/usr/lib/perl${VER}/${VERS}/site_perl \
        -Dsitearch=/usr/lib/perl${VER}/${VERS}/site_perl -Dvendorlib=/usr/lib/perl${VER}/${VERS}/vendor_perl \
        -Dvendorarch=/usr/lib/perl${VER}/${VERS}/vendor_perl >./.configure.log 2>&1 || exit 1
    touch ./.configured
fi

if [ ! -f ./.compiled ]; then
    echo "  ${YELLOW}Compiling PERL ${CYAN}${VERS}${NORMAL}"
    make -j$(nproc) >./.compiled.log 2>&1 || exit 1
    touch ./.compiled
fi

if [ ! -d $CUR/bin/perl-${VERSION} ]; then
    echo "  ${YELLOW}Installing PERL ${CYAN}${VERS}${NORMAL}"
    make DESTDIR=$CUR/bin/perl-${VERSION} install >./.installed.log 2>&1 || exit 1
fi


























