#!/bin/sh

#########################
## APPLICATION DETAILS ##
################################################################################
# Maintainer: Jose-Luis Rivas <ghostbar@riseup.net>
pkgname=bats
pkgver=1.11.0
pkgrel=0
pkgdesc="Bash Automated Testing System"
url="https://github.com/bats-core/bats-core"
arch="all"
license="MIT"
depends="bash"
#subpackages="$pkgname-doc"
source="-O $pkgname-$pkgver.zip https://github.com/bats-core/bats-core/archive/v$pkgver.zip"
builddir="bats-core-$pkgver"
pkgfile="${pkgname}-${pkgver}.zip"
pkgdir="${pkgname}-${pkgver}"
################################################################################

########################
# Extension Maintainer #
################################################################################
pkg_maintainer="CentralWare Development Centers"
pkg_maint_contact=""
################################################################################

get_source()
{
    echo "Getting current version information..."
    [ "${pkgver}" == "" ] && get_version

    if [ ! -f $CUR/src/${pkgfile} ]; then
        echo "Download SOURCE TARBALL from website (${pkgver})"
        mkdir -p $CUR/src/raw; cd $CUR/src
        wget -q --no-check-certificate $source
    fi

    if [ ! -d $CUR/src/${pkgdir} ]; then
        cd $CUR/src
        unzip ${pkgfile}
        mv $builddir $pkgdir
        if [ ! -d $CUR/src/raw/${pkgdir} ]; then
            cp $CUR/src/${pkgdir} $CUR/src/raw/ -R
        fi
    fi
}

src_depends()
{
    echo "Loading compilation dependencies"
}

src_build()
{
    get_source
    [ ! -d $CUR/src/${pkgdir} ] && $(echo "${RED}ERROR! ${MAGENTA}Cannot find working source directory!"; exit 1)

    cd $CUR/src/${pkgdir}

    echo "${CYAN}Testing...${NORMAL}"
    bash -c 'bin/bats --tap test'

    echo "${CYAN}Preparing...${NORMAL}"
    ./install.sh $CUR/ext/usr/local > $CUR/_install.log 2>&1 || exit 1

}



##>> SHARED FUNCTIONS (Update to shared location)
. ../functions

CPU=$(GetProcessorType)

clear
CUR=$(pwd)
ShowTitle
echo
echo "${WHITE}Extension ${GREEN}${pkgname}${NORMAL}"
echo

ExtClean
ExtLoadQuiet compiling wget bash python3.6

src_build




