#!/bin/sh
clear; CUR=$(pwd); OLD=$CUR; . /etc/init.d/tc-functions; . ../functions;       ##### TCL
TITLE="
${CYAN}        ######
${CYAN}       ##    ## ####
${CYAN}       ##        ##  ##     ##
${CYAN}        ######   ##  ###   ### ########
${CYAN}             ##  ##  #### #### ##     ## ##
${CYAN}       ##    ##  ##  ## ### ## ##     ## ##       ########
${CYAN}        ######   ##  ##     ## ########  ##       ##
${CYAN}                #### ##     ## ##        ##       ##             ${WHITE}#####
${CYAN}                     ##     ## ##        ##       ######        ${WHITE}##   ##
${CYAN}                   #           ##        ##       ##            ${WHITE}# ${BLUE}0 0 ${WHITE}#
${CYAN}  ######          ###                    ######## ##           ${WHITE}#   ${YELLOW}V   ${WHITE}#
${CYAN}    ##             #                              ########    ${WHITE}##       ##
${CYAN}    ##         ###    ### ####   ###    ###  ##### #####     ${WHITE}#           #
${CYAN}    ##        #  ##    ###    ##  ##     ##    ##   ##      ${WHITE}#             #
${CYAN}    ##       #   ##    ##     ##  ##     ##      ###        ${WHITE}#  #       #  #
${CYAN}    ##          ###    ##     ##  ##     ##      ###       ${YELLOW}@@${WHITE}##         ##${YELLOW}@@
${CYAN}    ##       # ###     ##     ##  ##     ##     ## ##    ${YELLOW}@@@@@@${WHITE}#       #${YELLOW}@@@@@@
${CYAN}    ##      ## ### #   ##     ##  ###   ###    ##   ##   ${YELLOW}@@@@@@@${WHITE}# ${RED}CDC ${WHITE}#${YELLOW}@@@@@@@
${CYAN}  ############  ###   ####   ####   #### ### ##### #####   ${YELLOW}@@@@@${WHITE} ##### ${YELLOW}@@@@@"
#------------------------------------------------------------------------------#
# This file is a part of a project which contains pieces from other projects   #
# belonging to potentially hundreds of individuals globally in an effort to    #
# bring together some of the best computing materials the world has to offer   #
# under a single roof with an automated core allowing a tailor-made experience #
# like no other. Some of these pieces may have originated from individuals,    #
# while others may have come from public distributions such as Alpine, Apache, #
# CentOS, Debian, Fedora, SlackWare, TinyCore, Zorin, etc. just to name a few. #
# This project will be ever changing throughout the entire Version 0.x.x life- #
# cycle and should NOT be considered a complete and/or functional system.      #
#------------------------------------------------------------------------------#
echo "${TITLE}${NORMAL}"; echo; SFX=$(GetProcessorType)
SXX=${SFX/x86_/x}; export CFLAGS CXXFLAGS LDFLAGS

ExtLoadQuiet git

REPOS="fltk_projects flnotify tinyx flwm tc-misc"

for REPO in $REPOS
do
    if [ ! -d $CUR/$REPO ]; then
        git clone https://github.com/tinycorelinux/${REPO}
    fi
done
