#!/bin/sh

      #####                   ##### ##         ##### ###       ##### #     ##         ##### ##         ##### #
   ######                  ######  #### #   ######  # ##    ######  ##    #### #   ######  #### #   ######  #
  ##   #  #    ##         ##   #  # ####   ##   #  #  ##   ##   #  # ##    ####   ##   #  # ####   ##   #  #
 #    #  #   #### #      #    #  #   ##   #    #  #   ##  #    #  #  ##    # #   #    #  #   ##   #    #  #
     #  #     ####           #  #             #  #    #       #  #    ##   #         #  #             #   #
    ## ##    # ##           ## ##            ## ##   #       ## ##    ##   #        ## ##            ## ##
    ## ##   #               ## ##            ## ##  #        ## ##     ##  #        ## ##            ## ##
    ## #####                ## ######        ## ####         ## ##     ##  #        ## ######        ## ##
    ## ## ###               ## #####         ## ##  ###      ## ##      ## #        ## #####         ## ##
    ## ##   ###             ## ##            ## ##    ##     ## ##      ## #        ## ##            ## ##
    #  ##    ###            #  ##            #  ##    ##     #  ##       ###        #  ##            #  ##
       #       ###             #                #     ##        #        ###           #                #
   ####         ###        ####         #   ####      ###   ####          ##       ####         #   ####           #
  #  #####        ###  #  #  ###########   #  ####    ##   #  #####               #  ###########   #  #############
 #    ###           ###  #     ######     #    ##     #   #     ##               #     ######     #     #########
 #                       #                #               #                      #                #
  ##                      ##               ##              ##                     ##               ##

    ###########################################################################################################
   ## This is the Build Manager for the Linux Kernel 6.1 or newer -- Older kernels are not directly supported ##
    ###########################################################################################################

CUR=$(pwd)
[ -f $CUR/../functions ] && . ../functions
ExtLoadQuiet wget

for i in $@
do
    case $i in
        *=*)
            case $i in
                version*)  VER=${i#*=} ;;
            esac ;;
        *)
            case $i in
                quiet)     vQUIET=1 ;;
                remote)    REMOTE=1 ;;
            esac ;;
    esac
done

#######################
### VERSION SCRAPER ###
################################################################################
[ -f versions ] && rm versions -f
if [ "${VER}" == "" ]; then
    wget -q -O versions http://www.kernel.org/finger_banner
    VER=$(cat versions | grep "stable version" | awk -F: '{print $2}'); VER=$(echo $VER)
fi
PRE=$(echo $VER | awk -F. '{print $1}')
################################################################################
CPU=$(GetProcessorType); PLT="64"; [ "$(echo $CPU | grep 64)" == "" ] && PLT=""

#if [ ! vREMOTE == 1 ]; then
#    clear
#    echo "${WHITE}SimpleNIX Builder${NORMAL}"
#    echo "${WHITE}=================${NORMAL}"
#    echo
#    echo "${CYAN}Project:                   ${GREEN}KERNEL ${MAGENTA}v${VER}${NORMAL}"
#    echo "${CYAN}Platform:                  ${GREEN}${CPU}${NORMAL}"
#    echo
#fi

##############
### KERNEL ###
################################################################################
cd $CUR; echo -n "${CYAN}Loading Support extensions"
ExtLoad wget compiletc perl5 ncursesw-dev bash mpc-dev udev-lib-dev texinfo coreutils glibc_apps gettext python3.6 elfutils-dev zsync

mkdir -p $CUR/src; cd $CUR/src
if [ ! -f linux-${VER}.tar.xz ]; then
    echo "${YELLOW}Downloading kernel ${VER} source code${NORMAL}"
    wget -q --no-check-certificate https://cdn.kernel.org/pub/linux/kernel/v${PRE}.x/linux-${VER}.tar.xz || exit 1
fi

if [ ! -d linux-${VER} ]; then
    echo "${YELLOW}Extracting Kernel Source${NORMAL}"
    tar -xf linux-${VER}.tar.xz || exit 1
fi

###################
##### PATCHES #####
###################
cd $CUR/src/linux-${VER}
if [ ! -f ./.patched ]; then
    echo "${YELLOW}Applying Kernel Patches${NORMAL}"
    for FILE in $CUR/_patches/*.patch
    do
        patch -Np1 -i $FILE > $CUR/_patch.log || exit 1
    done
    touch ./.patched
fi

cd $CUR/src/linux-${VER}
[ ! -f ./.config ] && cp $CUR/config ./.config
echo "${YELLOW}Configuring kernel ${GREEN}${VER}${NORMAL}"
echo -e "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n" > ./.blanks
echo -e "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n" >> ./.blanks
echo -e "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n" >> ./.blanks
echo -e "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n" >> ./.blanks
[ ! -f ./.config.ready ] && make oldconfig < ./.blanks > $CUR/_config.log 2>&1 && touch ./.config.ready
echo "${YELLOW}Compiling kernel${NORMAL}"
[ ! -f ./.compiled ] && time make -j$(nproc) bzImage > $CUR/_kernel.log 2>&1 && touch ./.compiled
echo "${YELLOW}Compiling modules${NORMAL}"
[ ! -f ./.modules ] && time make -j$(nproc) modules > $CUR/_modules.log 2>&1 && touch ./.modules

[ ! -d $CUR/src/modules ] && make INSTALL_MOD_PATH="$CUR/src/modules/usr/local" modules_install > $CUR/_modinst.log
echo "${YELLOW}Sorting Modules${NORMAL}"
cd $CUR/src; [ ! -f sorter.sh ] && wget -q https://raw.githubusercontent.com/tinycorelinux/sorter/refs/heads/master/sorter.sh && chmod +x sorter.sh
mkdir -p $CUR/src/output; cd $CUR/src/output
$CUR/src/sorter.sh ${VER}-tinycore${PLT} $CUR/src/modules > $CUR/_sorter.log
cd $CUR; rm config -f; cp src/linux-${VER}/.config $CUR/config -f
################################################################################


